"""_map.json: the JSON registry graph and `--since` file keys."""
import json, os

from . import MAP_ENGINE_VERSION
from .git import _git, _git_root
from .registry import commands_manifest


def _path_key(path):  # implements: ARCH-CHECK-006
    """Comparison key for a filesystem path: fully resolved, then case-folded.

    `abspath` is not enough where a git-derived path meets a caller-derived one.
    It normalizes separators and (with normcase) case, but leaves an 8.3 SHORT
    component alone: `C:/Users/RUNNER~1/...` from the caller and
    `C:/Users/runneradmin/...` from `git rev-parse --show-toplevel` (always long
    form) are the same directory and compare unequal. In `--since` that made every
    member fall out of the changed-set, so the gate reported a clean tree with a
    dangling tag still in it - a gate failing OPEN, silently, on Windows only.
    Found by the CI portability matrix on its first run (ARCH-PYFLOOR-040).

    realpath resolves the short form, and symlinks with it - a repo reached through
    a symlinked path hit the same mismatch on POSIX. Both sides of every comparison
    go through this one function, so resolution can never apply to just one of them.
    """
    return os.path.normcase(os.path.realpath(path))


def _since_changed_files(ref, code_root):
    """Return set of absolute paths changed since `ref`, or None on failure.

    Returns None as the fail-open signal: caller must fall back to full scan.
    """
    try:
        # core.quotepath=off: emit non-ASCII paths verbatim, not octal-escaped &
        # double-quoted — otherwise those files silently drop out of the since-set
        # and the gate falsely reports clean.
        diff = _git(["-c", "core.quotepath=off", "diff", "--name-only",
                     "{}...HEAD".format(ref)], cwd=code_root, timeout=10)
        if diff is None:
            return None
        # `git diff` emits paths relative to the repo ROOT, not to cwd. Resolve
        # the toplevel so these abspaths line up with member abspaths (which are
        # relative to code_root) even when code_root is a subdirectory of the
        # git root — otherwise the since-set and member-set never intersect and
        # the gate silently checks zero requirements. Falls back to code_root.
        root = _git_root(code_root)
        files = set()
        for line in diff.splitlines():
            line = line.strip()
            if line:
                files.add(_path_key(os.path.join(root, line)))
        return files
    except Exception:
        return None


def _utf8_safe(text):  # implements: ARCH-MAP-007  # implements: REQ-MAP-870
    """Text with any lone surrogate replaced by U+FFFD, so the write cannot fail.

    A lone surrogate has no UTF-8 encoding, so `open(..., encoding="utf-8").write()`
    raises UnicodeEncodeError and takes the whole `map` run down - and with it the
    gate's map-freshness check. It is not a theoretical input: os.walk hands back a
    filename whose bytes are not valid UTF-8 surrogate-escaped, and member paths go
    straight into the map. Losing one character beats losing the command.

    The fast path is a C-level encode that touches nothing; the per-character walk
    runs only for a string that genuinely cannot be encoded.
    """
    try:
        text.encode("utf-8")
        return text
    except UnicodeEncodeError:
        return "".join("\uFFFD" if 0xD800 <= ord(c) <= 0xDFFF else c for c in text)


def _build_json_text(data):  # implements: ARCH-MAP-007  # implements: REQ-MAP-870
    """The registry graph as a JSON string:
    {engine_version, repo, nodes, edges, upstream_edges, todos, roadmap, commands
    [, design][, health]}.
    json.dumps neutralizes any hostile id/title/body by construction — there is
    no markup context to break out of — so no extra escaping is needed."""
    payload = {"engine_version": MAP_ENGINE_VERSION, "repo": data.get("repo"),
               "nodes": data["nodes"], "edges": data["edges"],
               # `satisfies:` edges — the specification hierarchy. Computed since
               # ARCH-TRACE-020 and, until now, discarded here: the graph carried the
               # dependency axis and dropped the level axis on the floor.
               "upstream_edges": data.get("upstream_edges", []),
               "todos": data.get("todos", []),
               # ROADMAP.md's horizon items, beside TODO.md's versioned ones.
               # implements: REQ-VIEWER-999
               "roadmap": data.get("roadmap", []),
               # one row per calendar month of shipped releases
               # implements: REQ-HISTORY-1003
               "history": data.get("history", []),
               # the CLI, as data: the viewer documents the verbs it was generated by
               "commands": commands_manifest()}
    if data.get("design"):                      # implements: REQ-DESIGN-954
        payload["design"] = data["design"]
    if data.get("health"):                      # implements: REQ-HEALTH-968
        payload["health"] = data["health"]
    if data.get("planning"):
        payload["planning"] = data["planning"]
        payload["targets"] = data["planning"]  # legacy alias
    elif data.get("targets"):
        payload["targets"] = data["targets"]
    return _utf8_safe(json.dumps(payload, indent=2, ensure_ascii=False))


def render_json(data, reqs_dir):  # implements: ARCH-MAP-007  # implements: REQ-MAP-870
    """Write `_map.json`, the registry graph the viewer and any external front-end
    read."""
    out = os.path.join(reqs_dir, "_map.json")
    os.makedirs(reqs_dir, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(_build_json_text(data))
    return out
